descriptions = [
    "Buy groceries",
    "Finish report for work",
    "Call mom to wish her happy birthday",
    "Schedule dentist appointment",
    "Pay bills online",
    "Clean the house",
    "Pick up dry cleaning",
    "Research vacation destinations",
    "Prepare for the presentation",
    "Organize files and folders",
    "Go for a jog",
    "Read a chapter from the new book",
    "Attend yoga class at 6 pm",
    "Take the car for servicing",
    "Start learning a new language",
    "Sort and respond to emails",
    "Set up a meeting with the team",
    "Renew library books",
    "Fix leaking faucet in the bathroom",
    "Update resume and cover letter",
]